# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service

class TestTest():
  def setup_method(self, method):
    service = Service("/Users/seanlim/Downloads/chromedriver-mac-arm64/chromedriver")
    self.driver = webdriver.Chrome(service=service)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    test_cases = [
      [1, 2, 3],
      [5, 10, 15],
      [0, 0, 0],
      [3, 7, 10],
      [8, 8, 16],
      [12, 5, 17],
      [6, 9, 15],
      [11, 2, 13],
      [20, 30, 50],
      [100, 200, 300],
      [7, 1, 8],
      [14, 6, 20],
      [25, 18, 43],
      [45, 55, 100],
      [9, 0, 9]
    ]   
    for case in test_cases:
      self.driver.implicitly_wait(2)
      self.driver.get("https://htmlpreview.github.io/?https://raw.githubusercontent.com/seanl01/mapfile/main/adder.html")
      self.driver.set_window_size(1054, 985)
      self.driver.find_element(By.ID, "a").click()
      self.driver.find_element(By.ID, "a").send_keys(case[0])
      self.driver.find_element(By.ID, "b").click()
      self.driver.find_element(By.ID, "b").send_keys(case[1])
      self.driver.find_element(By.ID, "add").click()
      assert self.driver.find_element(By.ID, "output").text == str(case[2])
  
