# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://htmlpreview.github.io/?https://raw.githubusercontent.com/seanl01/mapfile/main/adder.html")
    self.driver.set_window_size(1054, 985)
    self.driver.find_element(By.ID, "a").click()
    self.driver.find_element(By.ID, "a").send_keys("1")
    self.driver.find_element(By.ID, "b").click()
    self.driver.find_element(By.ID, "b").send_keys("3")
    self.driver.find_element(By.ID, "add").click()
    assert self.driver.find_element(By.ID, "output").text == "4"
  
